name: Apocalypse
version: 0.1
main: net.richardsprojects.bukkit.apocalypse.Apocalypse
commands:
    start:
        description: Starts the game
        usage: /<command>
    timealive:
        description: Tells you the amount of time you have been alive.
        usage: /<command>
    credits:
        description: Displays the version and credits for the server.
        usage: /<command>
    stats:
        description: Lists your total kills, deaths and KD spread.
        usage: /<command>
    group:
        description: Offers a player that is currently online if they want to join to a group with you.
        usage: /<command> <player>
    